language: node_js
node_js:
  - 6
sudo: false
script:
  - '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash ./deploy.sh'
cache:
  directories:
    - node_modules
env:
  global:
    - secure: "Jg8aFf2lND1jokJ1d/KOuM/e9qhhvwh+HxZoAb0QRNz6llRhE5YiZjtCXb3jRJPTej1KrCtG/b2YaCS5hwmsX5IIquzGvsc6p3Ys+aV70Tlv9zTeIk1Q+cNjXlBuG7h1pgX9lHZ7XlXrpJd6QvIu3siPV14v61DT08F4/RAY37HK6RIpE994m/lxYC+OGRBhZl9I7m2lqKU/gLq6sERbrxn5fRqP8UHLbDh0oAFvARqEaUdZExmSF4loK6BnUKAedMmGUbe1FLX7LnjSLEKZPCt1KzcosL03eMkTIN3DNZyaUu82jQAfUGdi+YzIsxAOXfoLLsvSYkeInsFats2c4qznW4rKbZmqCoYLhYYnovs+1pQP+Bu8Zh0u3ZJ+CTqg95kv1FKYKCsLwoQ2+uI46X0cz6FlEDR/7k0CDSItwGkCR4bg0KAYJ6M3AS6xzjPfnNaLUknHQRFAaIdhMFK6a0PZzuezWVUJL5yBMoSp1iJz/2irWhkB4B5wWzeXv6earFHWeXc2aRchSOa4jXeFY6/w4wj/0B55WvXmNPxaHIWlSplfs55gWrI3jBVxqz6LByaY5AGI6YKOsTXB4CoTL1l/rya2bpNGWa/+HNQlKRQ2J6/3rab26aI7llFbDtpm7PxvRiwfFAoVyevEMK1ZdjizNc18+cXpHJ7UMR6ywpU="
